import "../styles/globals.css";
import "tippy.js/dist/tippy.css";

import { Inter } from "next/font/google";

import Header from "@/components/Header";

export const metadata = {
  title: "Yuu",
  description: "Generated by create next app",
};

const inter = Inter({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  style: ["normal"],
  variable: "--inter-font",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br" className={`${inter.variable}`}>
      <body>
        <Header />

        {children}
      </body>
    </html>
  );
}
